soc: qcom: Fix in-tree build for smcinvoke driver
TRACE_INCLUDE_PATH should be relative to include/trace/define_trace.h
(or you need to add a header search path option in Makefile explicitly).

Presumably, this issue was unnoticed because Yocto builds the kernel in
a separate output directory, and Kbuild automatically adds a search path
You cannot rely on this behavior.

If you build the kernel in-tree, you will see the following build error.

    CC      drivers/soc/qcom/smcinvoke/smcinvoke.o
  In file included from drivers/soc/qcom/smcinvoke/trace_smcinvoke.h:497,
                   from drivers/soc/qcom/smcinvoke/smcinvoke.c:44:
  ./include/trace/define_trace.h:95:42: fatal error: ./trace_smcinvoke.h: No such file or directory
     95 | #include TRACE_INCLUDE(TRACE_INCLUDE_FILE)
        |                                          ^

Signed-off-by: Masahiro Yamada <masahiro.yamada@canonical.com>