PENDING: iommu/arm-smmu-qcom: Fix compilation error
With config CONFIG_ARM_SMMU_QCOM_DEBUG on, fix compilation
error:
drivers/iommu/arm/arm-smmu/arm-smmu-qcom-debug.c:25:28:
error: 'struct qcom_smmu' has no member named 'cfg'.

Fixes: e48f5f98922c ("FROMLIST: iommu/arm-smmu: introduction of ACTLR for custom prefetcher settings")
Change-Id: Ie08cb0d4eefcd43482a82918c8d2ec21bf44e199
Signed-off-by: Zhenhua Huang <quic_zhenhuah@quicinc.com>
(cherry picked from commit a32a8bc6c677d87c0cb74f4ffd5b06683f95bdae)
Signed-off-by: Masahiro Yamada <masahiro.yamada@canonical.com>